---

- name: Cisco show version example
  hosts: 10.10.11.90
  gather_facts: false

  tasks:
    - name: run show version
      ios_command:
        commands: show version
      register: output

    - name: print output
      debug:
        var: output.stdout_lines
